version: '2'

services:  
  localstack:
    image: localstack/localstack
    hostname: localstack
    networks:
      nw:
        aliases:
          - localstack
    ports:
      - "4567-4584:4567-4584"
      - "8090:8080"
    environment:
      - LOCALSTACK_SERVICES=sqs,sns
      - LOCALSTACK_DEBUG=1
      - LOCALSTACK_DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-1
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
  
networks:
  nw: {}

